{% set name = "plottable" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plottable-{{ version }}.tar.gz
  sha256: 235d762a31c82129dc5bf74205c103a14b1e4393d0f921cc0231be5de884041d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - matplotlib-base
    - numpy
    - pandas
    - pillow

test:
  imports:
    - plottable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/znstrider/plottable
  summary: Beautifully customized tables with matplotlib
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
